// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB62mNAw29OzPd6VOqV8WwmSdX5GF21XMw',
    appId: '1:65869500118:web:d39765709023af1feec377',
    messagingSenderId: '65869500118',
    projectId: 'notifications-8d22c',
    authDomain: 'notifications-8d22c.firebaseapp.com',
    storageBucket: 'notifications-8d22c.appspot.com',
    measurementId: 'G-L8ZXBGBV50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdq0XiIwmLYq7Sp721gdRNJvTTAeCR-Ho',
    appId: '1:65869500118:android:93105d0c1bbe6a2feec377',
    messagingSenderId: '65869500118',
    projectId: 'notifications-8d22c',
    storageBucket: 'notifications-8d22c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgB2BrWPB4zxsHKbI3e9rSCLB7kEC7K1o',
    appId: '1:65869500118:ios:af7e713a7bcf5477eec377',
    messagingSenderId: '65869500118',
    projectId: 'notifications-8d22c',
    storageBucket: 'notifications-8d22c.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgB2BrWPB4zxsHKbI3e9rSCLB7kEC7K1o',
    appId: '1:65869500118:ios:10c61d6e71fd5a2feec377',
    messagingSenderId: '65869500118',
    projectId: 'notifications-8d22c',
    storageBucket: 'notifications-8d22c.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
